# Form implementation generated from reading ui file 'interest.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sqlite3  # Changed from mysql.connector to sqlite3
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS2
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


class Ui_Framintereste(object):
    def setupUi(self, Framintereste):
        Framintereste.setObjectName("Framintereste")
        Framintereste.resize(736, 584)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Framintereste.sizePolicy().hasHeightForWidth())
        Framintereste.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Framintereste)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=Framintereste)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(412, 301))
        self.widget_4.setStyleSheet("#widget_4{\n"
                                    "border:2px solid gray;\n"
                                    "border-radius:50px;\n"
                                    "}\n"
                                    "QLabel{\n"
                                    "background:#9A79BA;\n"
                                    "}\n"
                                    "\n"
                                    "QLabel {\n"
                                    "\n"
                                    "    background-color: #E6D7FA;\n"
                                    "    color: #653C87;\n"
                                    "    font-family: \'Segoe UI\', sans-serif;\n"
                                    "    font-size: 16px;\n"
                                    "    font-weight: 600;\n"
                                    "    padding: 8px;\n"
                                    "    border: 2px solid #653C87;\n"
                                    "    border-radius: 10px;\n"
                                    "    transition: background-color 0.3s ease, border-color 0.3s ease;\n"
                                    "}\n"
                                    "\n"
                                    "QLabel:hover {\n"
                                    "    background-color: #D4C2EF;  /* Slightly darker background on hover */\n"
                                    "    border-color: #553075;  /* Darker border on hover */\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit {\n"
                                    "    border: 2px solid #9A79BA;\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 8px;\n"
                                    "    font-family: \'Segoe UI\', sans-serif;\n"
                                    "    font-size: 18px;\n"
                                    "    color: #653C87;\n"
                                    "    background-color: #FFFFFF;\n"
                                    "    transition: background-color 0.3s ease, border-color 0.3s ease;\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit:hover {\n"
                                    "    background-color: #F5F0FA;  /* Slightly lighter background on hover */\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit:focus {\n"
                                    "    border: 2px solid #653C87;  /* Darker border on focus */\n"
                                    "    background-color: #F5F5F5;  /* Slightly lighter background on focus */\n"
                                    "}\n"
                                    "")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(15, 15, 15, 13)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_12 = QtWidgets.QFrame(parent=self.widget_4)
        self.frame_12.setMaximumSize(QtCore.QSize(392, 62))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_17.setMinimumSize(QtCore.QSize(142, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.frame_12)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_12.addWidget(self.lineEdit_14)
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_9 = QtWidgets.QFrame(parent=self.widget_4)
        self.frame_9.setMaximumSize(QtCore.QSize(392, 62))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_14.setMinimumSize(QtCore.QSize(188, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame_9)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_9.addWidget(self.lineEdit_11)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_13 = QtWidgets.QFrame(parent=self.widget_4)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 62))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_2.setMaximumSize(QtCore.QSize(142, 16777215))
        self.pushButton_2.clicked.connect(self.interest)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: #653C87; /* Dark purple background */\n"
                                        "    color: #FFFFFF; /* White text */\n"
                                        "    font-family: \'Segoe UI\', sans-serif; /* Font family */\n"
                                        "    font-size: 14px; /* Font size */\n"
                                        "    font-weight: bold; /* Bold text */\n"
                                        "    padding: 10px 20px; /* Padding */\n"
                                        "    border: 2px solid #9A79BA; /* Light purple border */\n"
                                        "    border-radius: 10px; /* Rounded corners */\n"
                                        "    transition: background-color 0.3s ease, border-color 0.3s ease; /* Smooth transition */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #9A79BA; /* Light purple background on hover */\n"
                                        "    border-color: #653C87; /* Dark purple border on hover */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: #E6D7FA; /* Lightest purple background on press */\n"
                                        "    border-color: #553075; /* Darker purple border on press */\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_13)
        self.horizontalLayout.addWidget(self.widget_4)

        self.retranslateUi(Framintereste)
        QtCore.QMetaObject.connectSlotsByName(Framintereste)

    def retranslateUi(self, Framintereste):
        try:
            # Connect to the SQLite database
            con = sqlite3.connect(resource_path('db/firm_management.db'))  # Changed to SQLite
            cursor = con.cursor()

            # Execute the query to fetch interest rate
            cursor.execute("SELECT * FROM funds")
            rows = cursor.fetchone()

            # Debugging logs
            print("rows:", rows)

            _translate = QtCore.QCoreApplication.translate
            Framintereste.setWindowTitle(_translate("Framintereste", "Frame"))
            self.label_17.setText(_translate("Framintereste", "current interest rate(%)"))

            # Handle cases where rows or rows[4] is None
            if rows and rows[4] is not None:
                interest_rate = rows[4]
            else:
                interest_rate = 0  # Default value if no valid interest rate is found

            # Update the UI field with the interest rate
            self.lineEdit_14.setText(str(interest_rate))
            self.lineEdit_14.setReadOnly(True)
            self.label_14.setText(_translate("Framintereste", "new interest rate(%)"))
            self.pushButton_2.setText(_translate("Framintereste", "Change"))

        except sqlite3.Error as e:  # Changed to sqlite3.Error
            print(f"Database error: {e}")

        except Exception as e:
            print(f"Unexpected error: {e}")

        finally:
            if con:
                cursor.close()
                con.close()

    def interest(self):
        try:
            inte = self.lineEdit_11.text()  # Get the value from the input field
            con = sqlite3.connect(resource_path('db/firm_management.db'))  # Changed to SQLite
            cursor = con.cursor()

            # Make sure the query is correctly parameterized (using a tuple for parameters)
            query = "UPDATE funds SET interest = ?"
            cursor.execute(query, (inte,))  # Passing 'inte' as a tuple

            con.commit()
            QtWidgets.QMessageBox.information(None, "Success", "Record updated successfully!")

        except Exception as e:
            print(f"Error: {e}")