# Form implementation generated from reading ui file 'member_report.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sqlite3  # Importing SQLite3 instead of MySQL
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS2
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

class Ui_reportFrame(object):
    username = None
    aadhar = None
    mobile = None
    email = None
    city = None
    joindate = None
    nominee_name = None
    nominee_aadhar = None

    funds = None
    debt = None

    def setupUi(self, reportFrame):
        reportFrame.setObjectName("reportFrame")
        reportFrame.resize(868, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(reportFrame.sizePolicy().hasHeightForWidth())
        reportFrame.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(reportFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=reportFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 410))
        self.widget.setStyleSheet("#widget\n"
                                  "{\n"
                                  "border:2px solid gray;\n"
                                  "border-radius:50px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setStyleSheet("\n"
                                    "QLineEdit {\n"
                                    "    border: 2px solid #9A79BA;\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 8px;\n"
                                    "    font-family: \'Segoe UI\', sans-serif;\n"
                                    "    font-size: 19px;\n"
                                    "    color: #653C87;\n"
                                    "    background-color: #FFFFFF;\n"
                                    "    transition: background-color 0.3s ease, border-color 0.3s ease;\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit:hover {\n"
                                    "    background-color: #F5F0FA;  /* Slightly lighter background on hover */\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit:focus {\n"
                                    "    border: 2px solid #653C87;  /* Darker border on focus */\n"
                                    "    background-color: #F5F5F5;  /* Slightly lighter background on focus */\n"
                                    "}\n"
                                    "")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(142, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: #653C87; /* Dark purple background */\n"
                                        "    color: #FFFFFF; /* White text */\n"
                                        "    font-family: \'Segoe UI\', sans-serif; /* Font family */\n"
                                        "    font-size: 14px; /* Font size */\n"
                                        "    font-weight: bold; /* Bold text */\n"
                                        "    padding: 10px 20px; /* Padding */\n"
                                        "    border: 2px solid #9A79BA; /* Light purple border */\n"
                                        "    border-radius: 10px; /* Rounded corners */\n"
                                        "    transition: background-color 0.3s ease, border-color 0.3s ease; /* Smooth transition */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #9A79BA; /* Light purple background on hover */\n"
                                        "    border-color: #653C87; /* Dark purple border on hover */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: #E6D7FA; /* Lightest purple background on press */\n"
                                        "    border-color: #553075; /* Darker purple border on press */\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(self.fetch_data)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(reportFrame)
        QtCore.QMetaObject.connectSlotsByName(reportFrame)

    def fetch_data(self, reportFrame):
        client_id = self.lineEdit.text()
        if not client_id:
            QMessageBox.warning(None, 'Failed', 'Invalid client id')
            return

        try:
            # Connect to the SQLite database
            connection = sqlite3.connect(resource_path('db/firm_management.db'))  # Changed to SQLite
            cursor = connection.cursor()

            # Query the database
            query = "SELECT * FROM addmember WHERE userid = ?"
            cursor.execute(query, (client_id,))
            result = cursor.fetchone()

            if result:
                # Unpack the result
                sr, userid, username, aadhar, mobile, email, city, joindate, nominyname, nominyaadhar = result
                self.username = result[2]
                self.aadhar = result[3]
                self.mobile = result[4]
                self.email = result[5]
                self.city = result[6]
                self.joindate = result[7]
                self.nominee_name = result[8]
                self.nominee_aadhar = result[9]
                # Update the textEdit with fetched data

            else:
                QMessageBox.warning(None, 'Failed', "No record found on particular id")

            query = "SELECT funds FROM funds WHERE id = ?"
            cursor.execute(query, (client_id,))
            result = cursor.fetchone()
            if result:
                self.funds = result[0]
                if self.funds > 0:
                    self.funds = result[0]
                    self.debt = 0
                else:
                    self.funds = 0
                    self.debt = result[0]

            else:
                pass
            self.see()
        except sqlite3.Error as e:  # Changed to handle SQLite errors
            print(e)
            QMessageBox.warning(None, 'Failed', str(e))

        finally:
            if connection:
                cursor.close()
                connection.close()

    def retranslateUi(self, reportFrame):
        _translate = QtCore.QCoreApplication.translate
        reportFrame.setWindowTitle(_translate("reportFrame", "Frame"))
        self.lineEdit.setPlaceholderText(_translate("reportFrame", "Enter id"))
        self.pushButton_2.setText(_translate("reportFrame", "Check"))
        self.textEdit.setHtml(_translate("reportFrame",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "hr { height: 1px; border-width: 0; }\n"
                                         "li.unchecked::marker { content: \"\\2610\"; }\n"
                                         "li.checked::marker { content: \"\\2612\"; }\n"
                                         "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; vertical-align:super;\">***The member report gives on this section is base on his past record and based on his/her amount and debited loan please enter the unique client code above four digit and clicked button *****</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">name of client : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.username}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">total debt on firms : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.debt}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">total deposit : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.funds}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">aadhar number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.aadhar}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">email id : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.email}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">join date : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.joindate}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">city : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.city}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">aadhar number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.aadhar}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">mobile number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.mobile}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">nomine name : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.nominee_name}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">nomine aadhar :-</span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.nominee_aadhar}</span></p>\n"
                                         "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700; color:#000000; vertical-align:super;\">caution : this information only for admin purpose </span></p></body></html>"))

    def see(self):
        _translate = QtCore.QCoreApplication.translate

        self.textEdit.setHtml(_translate("reportFrame",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "hr { height: 1px; border-width: 0; }\n"
                                         "li.unchecked::marker { content: \"\\2610\"; }\n"
                                         "li.checked::marker { content: \"\\2612\"; }\n"
                                         "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; vertical-align:super;\">***The member report gives on this section is base on his past record and based on his/her amount and debited loan please enter the unique client code above four digit and clicked button *****</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">name of client : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.username}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">total debt on firms : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.debt}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">total deposit : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.funds}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">aadhar number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.aadhar}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">email id : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.email}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">join date : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.joindate}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">city : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.city}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">aadhar number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.aadhar}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">mobile number : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.mobile}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">nomine name : </span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.nominee_name}</span></p>\n"
                                         f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:700; color:#9966c6; vertical-align:super;\">nomine aadhar :-</span><span style=\" font-size:24pt; font-weight:700; color:#000000; vertical-align:super;\">{self.nominee_aadhar}</span></p>\n"
                                         "<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700; color:#000000; vertical-align:super;\">caution : this information only for admin purpose </span></p></body></html>"))
