# Form implementation generated from reading ui file 'loan1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Framloan(object):
    def setupUi(self, Framloan):
        Framloan.setObjectName("Framloan")
        Framloan.resize(916, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Framloan.sizePolicy().hasHeightForWidth())
        Framloan.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtWidgets.QGridLayout(Framloan)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=Framloan)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QFrame:addmember{\n"
"border:none;\n"
"}\n"
"#frame{\n"
"border:2px solid gray;\n"
"border-radius:20px;\n"
"}\n"
"QLabel {\n"
"\n"
"    background-color: #E6D7FA;\n"
"    color: #653C87;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px;\n"
"    border: 2px solid #653C87;\n"
"    border-radius: 10px;\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #D4C2EF;  /* Slightly darker background on hover */\n"
"    border-color: #553075;  /* Darker border on hover */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #9A79BA;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 14px;\n"
"    color: #653C87;\n"
"    background-color: #FFFFFF;\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #F5F0FA;  /* Slightly lighter background on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #653C87;  /* Darker border on focus */\n"
"    background-color: #F5F5F5;  /* Slightly lighter background on focus */\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 54))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 58))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;\n"
"background:none;\n"
"font: 700 20pt \"Verdana\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setHorizontalSpacing(51)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #653C87; /* Dark purple background */\n"
"    color: #FFFFFF; /* White text */\n"
"    font-family: \'Segoe UI\', sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px 20px; /* Padding */\n"
"    border: 2px solid #9A79BA; /* Light purple border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9A79BA; /* Light purple background on hover */\n"
"    border-color: #653C87; /* Dark purple border on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D7FA; /* Lightest purple background on press */\n"
"    border-color: #553075; /* Darker purple border on press */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_3.setMaximumSize(QtCore.QSize(121, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #653C87; /* Dark purple background */\n"
"    color: #FFFFFF; /* White text */\n"
"    font-family: \'Segoe UI\', sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px 20px; /* Padding */\n"
"    border: 2px solid #9A79BA; /* Light purple border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9A79BA; /* Light purple background on hover */\n"
"    border-color: #653C87; /* Dark purple border on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D7FA; /* Lightest purple background on press */\n"
"    border-color: #553075; /* Darker purple border on press */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_4.setMaximumSize(QtCore.QSize(92, 16777215))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #653C87; /* Dark purple background */\n"
"    color: #FFFFFF; /* White text */\n"
"    font-family: \'Segoe UI\', sans-serif; /* Font family */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    padding: 10px 20px; /* Padding */\n"
"    border: 2px solid #9A79BA; /* Light purple border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9A79BA; /* Light purple background on hover */\n"
"    border-color: #653C87; /* Dark purple border on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D7FA; /* Lightest purple background on press */\n"
"    border-color: #553075; /* Darker purple border on press */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Framloan)
        QtCore.QMetaObject.connectSlotsByName(Framloan)

    def retranslateUi(self, Framloan):
        _translate = QtCore.QCoreApplication.translate
        Framloan.setWindowTitle(_translate("Framloan", "Frame"))
        self.label_4.setText(_translate("Framloan", "Loan"))
        self.pushButton_2.setText(_translate("Framloan", "loan approved"))
        self.pushButton_3.setText(_translate("Framloan", "bad debt"))
        self.label_5.setText(_translate("Framloan", "Name"))
        self.label_6.setText(_translate("Framloan", "Amount"))
        self.pushButton_4.setText(_translate("Framloan", "Submit"))
